name: 'Docker Build'
description: 'Build Docker image with caching and optional push'
author: 'Learning Project'

inputs:
  push:
    description: 'Whether to push the image to registry'
    required: false
    default: false
  tags:
    description: 'Docker image tags (comma separated)'
    required: false
    default: 'test'
  platforms:
    description: 'Target platforms for build'
    required: false
    default: 'linux/amd64'
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  build-args:
    description: 'Build arguments (multiline)'
    required: false
    default: ''
  labels:
    description: 'Docker labels (multiline)'
    required: false
    default: ''

outputs:
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  metadata:
    description: 'Build metadata'
    value: ${{ steps.build.outputs.metadata }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ inputs.build-args }}
